language: csharp
solution: SudokuSolver/SudokuSolver.sln
install:
  - nuget restore SudokuSolver/SudokuSolver.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SudokuSolver/SudokuSolver.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./SudokuSolver/SudokuSolverTests/bin/Release/SudokuSolverTests.dll